#!/bin/sh

WORKING_DIR="/home/muklis"
APP="usermanagement"
VERSION="0.0.1-SNAPSHOT"
APP_NAME="$WORKING_DIR/$APP/usermanagement-$VERSION.jar"
ROOT_APP="$WORKING_DIR/$APP"

CONF="-server -XX:MaxNewSize=64m -XX:NewSize=64m"

JVM_ARGSD="$CONF -Dspring.profiles.active=development"
JVM_ARGSP="$CONF -Dspring.profiles.active=production"
JVM_ARGST="$CONF -Dspring.profiles.active=testing"

if [ "$1" ]; then

        if [ "$1" = "start" ];then

        if [ "$2" = "development" ]; then
        echo "starting development $APP_NAME..."
        nohup java -DROOT_APP=$ROOT_APP -jar $JVM_ARGSD $APP_NAME </dev/null >/dev/null 2>&1 &

        elif [ "$2" = "testing" ]; then
        echo "starting testing $APP_NAME..."
        nohup java -DROOT_APP=$ROOT_APP -jar $JVM_ARGST $APP_NAME </dev/null >/dev/null 2>&1 &

        elif [ "$2" = "production" ]; then
        echo "starting production $APP_NAME..."
        nohup java -DROOT_APP=$ROOT_APP -jar $JVM_ARGSP $APP_NAME </dev/null >/dev/null 2>&1 &

        else
        echo "Please give argument 'development', 'testing' or 'production' ..."

        fi

        elif [ "$1" = "stop" ]; then
                echo "stopping $APP_NAME..."
                pkill -f $APP_NAME
                echo "$APP_NAME successfully stopped."

        fi


else
    echo "Please give first argument 'start' or 'stop' and the second argument is 'development', 'testing' or 'production'"
fi
