server:
  port: 20003

management:
  port: 20004
  address: localhost
endpoints:
  shutdown:
    enabled: true

spring:
  datasource:
    url: jdbc:mysql://localhost/codecika-usermanagement
    driver-class-name: com.mysql.jdbc.Driver
    username: usermanagement
    password: welcome1
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connectionTestQuery: SELECT 1
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
      maximumPoolSize: 10
  messages:
    basename: messages/messages
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  mail:
    protocol: smtp
    host: smtp.gmail.com
    port: 587
    username: cariparkir.indonesia@gmail.com
    password: welcomecp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

keycloak:
  realm: cari-parkir
  auth-server-url: http://localhost:8080/auth
  ssl-required: external
  resource: backend-api
  credentials:
    secret: aea20e1d-4aa6-47cf-8058-ddfbe3d86643
  securityConstraints[0]:
      authRoles[0]: admin
      authRoles[1]: superadmin
      authRoles[2]: admin_usermanagement
      authRoles[3]: admin_view
      authRoles[4]: admin_location
      securityCollections[0]:
        name: admin api
        patterns[0]: /user-service/api/v1/admin/usermanagement/*

username:
  admin:
    keycloak: admin
password:
  admin:
    keycloak: welcome1
  default: welcome1

ip:
  whitelist: 127.0.0.1,localhost,0:0:0:0:0:0:0:1

parkinglocation:
  server: http://localhost:20005

---

spring:
  profiles: development
  datasource:
    url: jdbc:mysql://nostra-data-tier-01:3306/usermanagement
    username: usermanagement
    password: welcome1

keycloak:
  auth-server-url: http://cariparkir.nostratech.com:10001/auth
  credentials:
    secret: 054b4b90-c3bb-4762-812e-0779291a1fef

username:
  admin:
    keycloak: keycloak
password:
  admin:
    keycloak: welcome1

ip:
  whitelist: 127.0.0.1,localhost,0:0:0:0:0:0:0:1,172.16.0.11

parkinglocation:
  server: http://cariparkir.nostratech.com:20005

---

spring:
  profiles: production
  datasource:
    url: jdbc:mysql://10.0.182.47:3306/usermanagement?useSSL=false
    username: usermanagement
    password: ezP@db2017

keycloak:
  auth-server-url: https://auth.cariparkir.co.id/auth
  credentials:
    secret: d2929f26-0fb1-4d49-837e-c7b8ede2b173

username:
  admin:
    keycloak: admin
password:
  admin:
    keycloak: ezP@kcweb4adm!n

ip:
  whitelist: 127.0.0.1,localhost

parkinglocation:
  server: http://parkinglocation-service:20005

---
spring:
  profiles: sit
  datasource:
    url: jdbc:mysql://10.0.0.62:3306/usermanagement?useSSL=false
    username: usermanagement
    password: Welcome1!

keycloak:
  auth-server-url: http://sit.cariparkir.co.id/auth
  credentials:
    secret: d2929f26-0fb1-4d49-837e-c7b8ede2b173

username:
  admin:
    keycloak: admin
password:
  admin:
    keycloak: welcome1

ip:
  whitelist: 127.0.0.1,localhost,0:0:0:0:0:0:0:1,10.0.0.5,13.76.214.116,40.83.176.102,52.187.19.179,52.187.56.226,52.163.112.215,52.163.217.179,52.163.219.6,52.163.222.2,52.163.221.128
  
parkinglocation:
  server: http://parkinglocation-service:20005

---

spring:
  profiles: testing_environment
  datasource:
    url: jdbc:mysql://localhost:3306/location
    username: location
    password: Welcome1!

keycloak:
  auth-server-url: http://localhost:8080/auth
  credentials:
    secret: d2929f26-0fb1-4d49-837e-c7b8ede2b173

---

email:
  subject:
    forgot: Forgot Password
    landingpage: Consumer feetback from web page
    cs: CS Cari Parkir Respone Email
  cs: support@cariparkir.co.id

template:
  forgot: forgot_password.ftl
  landingpage: email_landingPage.ftl
  cs: email_cs.ftl

---
service:
  transaction: http://nostra-cari-parkir:20009
  astra: https://astradtaisapimint.azure-api.net


scheduler:
  time:
    user: 0 0 23 * * *